project-2/artikel/urls.py
from django.urls import path, re_path
from .views import (
                    ArtikelListView,
                    ArtikelDetailView,
                    ArtikelKategoriListView,
                    ArtikelCreateView,
                    ArtikelManageView,
                    ArtikelDeleteView,
                    ArtikelUpdateView
                    )

urlpatterns = [
    re_path('manage/update/(?P<pk>\d+)', ArtikelUpdateView.as_view(), name='update'),
    re_path('manage/delete/(?P<pk>\d+)', ArtikelDeleteView.as_view(), name='delete'),
    re_path('manage/', ArtikelManageView.as_view(), name='manage'),
    re_path('tambah/', ArtikelCreateView.as_view(), name='create'),
    re_path('kategori/(?P<kategori>[\w]+)/(?P<page>\d+)', ArtikelKategoriListView.as_view(), name='kategori'),
    re_path('detail/(?P<slug>[\w-]+)', ArtikelDetailView.as_view(), name='detail'),
    re_path('(?P<page>\d+)', ArtikelListView.as_view(), name='list'),
]

project-2/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import BlogHomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('artikel/', include(('artikel.urls', 'artikel'), namespace='artikel')),
    re_path('', BlogHomeView.as_view(), name='home'),
]

project-2/artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

class Artikel(models.Model):
    judul = models.CharField(max_length=255)
    isi   = models.TextField()
    kategori = models.CharField(max_length=255)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug':self.slug}
        return reverse('artikel:detail',kwargs=url_slug)

    def __str__(self):
        return '{}. {}'.format(self.id, self.judul)

project-2/artikel/forms.py
from django.forms import ModelForm
from .models import Artikel

class ArtikelForm(ModelForm):
    class Meta:
        model = Artikel
        fields = [
            'judul',
            'isi',
            'kategori'
        ]

project-2/artikel/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView, 
    DeleteView, 
    UpdateView,
    )
from django.urls import reverse_lazy
# Create your views here.
from .models import Artikel
from.forms import ArtikelForm

class ArtikelUpdateView(UpdateView):
    form_class = ArtikelForm
    model = Artikel
    template_name = 'artikel/artikel_update.html'

class ArtikelDeleteView(DeleteView):
    model = Artikel
    template_name = 'artikel/artikel_deleteconf.html'
    success_url = reverse_lazy('artikel:manage')


class ArtikelManageView(ListView):
    model = Artikel
    template_name = 'artikel/artikel_manage.html'
    context_object_name = 'artikel_list'

class ArtikelCreateView(CreateView):
    form_class = ArtikelForm
    template_name = 'artikel/artikel_create.html'


class ArtikelPerKategori():
    model = Artikel
    
    def get_latest_artikel(self):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        queryset = []

        for kategori in kategori_list:
            artikel = self.model.objects.filter(kategori=kategori).latest('published')
            queryset.append(artikel)
        return queryset


class ArtikelKategoriListView(ListView):
    model = Artikel
    template_name = 'artikel/artikel_kategoriList.html'
    context_object_name = 'artikel_list'
    ordering = ['-published']
    paginate_by = 3

    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
        return super().get_queryset()

    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct().exclude(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)


class ArtikelListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_list.html"
    context_object_name = 'artikel_list'
    ordering = ['-published']
    paginate_by = 3

    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = 'artikel/artikel_detail.html'
    context_object_name = 'artikel'

    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})

        artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(id=self.object.id)
        self.kwargs.update({'artikel_serupa':artikel_serupa})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)
    

    

project-2/blog/views.py
from artikel.views import ArtikelPerKategori
from django.views.generic import TemplateView


class BlogHomeView(TemplateView, ArtikelPerKategori):
    template_name = 'index.html'

    def get_context_data(self):
        querysets = self.get_latest_artikel()
        context = {
            'latest_artikel' : querysets
        }
        return context

project-2/artikel/templates/artikel/artikel_create.html
{% extends 'base.html' %}

{% block page_title %}
Create
{% endblock page_title %}

{% block contents %}
<h1>Tambah Artikel</h1>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="{{form.judul.id_for_label}}" class="form-label">{{form.judul.label}}:</label>
        <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="form.judul.max" required
            id="{{form.judul.id_for_label}}">
    </div>
    <div class="mb-3">
        <label for="{{form.isi.id_for_label}}" class="form-label">{{form.isi.label}}:</label>
        <textarea class="form-control" name="{{form.isi.name}}" rows="10" required
            id="{{form.isi.id_for_label}}"></textarea>
    </div>
    <div class="mb-3">
        <label for="{{form.kategori.id_for_label}}" class="form-label">{{form.kategori.label}}:</label>
        <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="form.kategori.max" required
            id="{{form.kategori.id_for_label}}">
    </div>
    <button type="submit" class="btn btn-primary">Tambahkan</button>
</form>
{% endblock contents %}

project-2/artikel/templates/artikel/artikel_deleteconf.html
{% extends 'base.html' %}

{% block page_title %}
Delete Artikel
{% endblock page_title %}

{% block contents %}
<h1>Delete Artikel Confirmation</h1>
<p>Apakah Anda yakin ingin menghapus artikel berikut:</p>
<h3>{{artikel.judul}}</h3>
<p>{{artikel.published}}</p>
<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-primary">Ya</button>
    <a class="btn btn-outline-danger" href="{% url 'artikel:manage' %}">Tidak</a>
</form>
{% endblock contents %}

project-2/artikel/templates/artikel/artikel_detail.html
{% extends 'base.html' %}

{% block page_title %}
{{artikel.judul}}
{% endblock page_title %}

{% block contents %}
<div class="row">
    <div class="col-md-8">
        <h1>{{artikel.judul}}</h1>
        <h5>Kategori: {{artikel.kategori}} | {{artikel.published}}</h5>
        <p>{{artikel.isi}}</p>
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">

            {% for kategori in kategori_list %}
            <li class="list-group-item">
                <a href="{% url 'artikel:kategori' kategori 1 %}">{{kategori}}</a>
            </li>
            {% endfor %}
            <h3>Artikel Serupa</h3>
            <ul class="list-group list-group-flush">

                {% for artikel in artikel_serupa %}
                <li class="list-group-item">
                    <h5>
                        <a href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a>
                    </h5>
                    <p>{{artikel.published|date}}</p>
                </li>
                {% endfor %}

            </ul>

        </ul>
    </div>
</div>
</div>
{% endblock contents %}

project-2/artikel/templates/artikel/artikel_kategoriList.html
{% extends 'base.html' %}

{% block page_title %}
Artikel
{% endblock page_title %}

{% block contents %}

<div class="row">
    <div class="col-md-8">
        <h2 class="border-bottom">{{kategori}}</h2>
        {% if is_paginated %}

        <nav aria-label="artikelPage">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                        href="{% url 'artikel:kategori' kategori page_obj.previous_page_number %}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}

                {% for page in paginator.page_range %}
                {% if page is page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link" href="#">{{page}}</span>
                </li>

                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'artikel:kategori' kategori page %}">{{page}}</a>
                </li>

                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'artikel:kategori' kategori page_obj.next_page_number %}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
                {% endif %}

            </ul>
        </nav>

        {% endif %}

        {% for artikel in artikel_list %}
        <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
        <p>{{artikel.published}}</p>
        <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a
                href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
        {% endfor %}
    </div>
    <div class="col-sm">
        <h3 class="border-bottom">Kategori Lainnya</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a href="{% url 'artikel:list' 1 %}"><b>Semua Kategori</b></a>

                {% for kategori in kategori_list %}
            </li>
            <li class="list-group-item">
                <a href="{% url 'artikel:kategori' kategori 1 %}">{{kategori}}</a>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>


{% endblock contents %}

project-2/artikel/templates/artikel/artikel_list.html
{% extends 'base.html' %}

{% block page_title %}
Artikel
{% endblock page_title %}

{% block contents %}

<div class="row">
    <div class="col-md-8">
        {% if is_paginated %}

        <nav aria-label="artikelPage">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'artikel:list' page_obj.previous_page_number %}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}

                {% for page in paginator.page_range %}
                {% if page is page_obj.number %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link" href="#">{{page}}</span>
                </li>

                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a>
                </li>

                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'artikel:list' page_obj.next_page_number %}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Next</a>
                </li>
                {% endif %}

            </ul>
        </nav>

        {% endif %}

        {% for artikel in artikel_list %}
        <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
        <p>Kategori: {{artikel.kategori}} | {{artikel.published}}</p>
        <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a
                href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
        {% endfor %}
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">

            {% for kategori in kategori_list %}
            <li class="list-group-item">
                <a href="{% url 'artikel:kategori' kategori 1 %}">{{kategori}}</a>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>


{% endblock contents %}

project-2/artikel/templates/artikel/artikel_manage.html
{% extends 'base.html' %}

{% block page_title %}
Manage Artikel
{% endblock page_title %}

{% block contents %}
<h1>Manage Artikel</h1>
<div class="d-grid gap-2">
    <a type="button" class="btn btn-primary" href="{% url 'artikel:create' %}">Tambah Artikel</a>
</div>
<table class="table mt-4">
    <thead class="table-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            <th scope="col">Kategori</th>
            <th scope="col">Published</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>

        {% for artikel in artikel_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{artikel.judul}}</td>
            <td>{{artikel.kategori}}</td>
            <td>{{artikel.published}}</td>
            <td>
                <a type="button" class="btn btn-warning" href="{% url 'artikel:update' artikel.id %}">Edit</a>
                <a type="button" class="btn btn-danger" href="{% url 'artikel:delete' artikel.id %}">Delete</a>
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock contents %}

project-2/artikel/templates/artikel/artikel_update.html
{% extends 'base.html' %}

{% block page_title %}
Update
{% endblock page_title %}

{% block contents %}
<h1>Update Artikel</h1>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="{{form.judul.id_for_label}}" class="form-label">{{form.judul.label}}:</label>
        <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="form.judul.max" required
            id="{{form.judul.id_for_label}}" value="{{form.judul.value}}">
    </div>
    <div class="mb-3">
        <label for="{{form.isi.id_for_label}}" class="form-label">{{form.isi.label}}:</label>
        <textarea class="form-control" name="{{form.isi.name}}" rows="10" required
            id="{{form.isi.id_for_label}}">{{form.isi.value}}</textarea>
    </div>
    <div class="mb-3">
        <label for="{{form.kategori.id_for_label}}" class="form-label">{{form.kategori.label}}:</label>
        <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="form.kategori.max" required
            id="{{form.kategori.id_for_label}}" value="{{form.kategori.value}}">
    </div>
    <button type="submit" class="btn btn-warning">Update</button>
    <a class="btn btn-danger" href="{% url 'artikel:manage' %}">Tidak</a>
</form>
{% endblock contents %}

project-2/templates/base.html
{% load static %}
<html lang="en">

<head>
    <title>

        {% block page_title %}

        {% endblock page_title %}

    </title>


    {% include 'snippets/styles.html' %}
</head>

<body>
    {% include 'snippets/navbar.html' %}
    <div class="container" style="margin-top: 100px">

        {% block contents %}

        {% endblock contents %}

    </div>

    {% include 'snippets/scripts.html' %}
</body>

</html>

project-2/templates/index.html
{% extends 'base.html' %}

{% block page_title %}
Home
{% endblock page_title %}

{% block contents %}
<h1>Home</h1>
<div class="row">
    {% for artikel in latest_artikel %}
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{artikel.kategori}}</h5>
                <h6 class="card-subtitle mb-2 text-dark">{{artikel.judul}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{artikel.published|date}}</h6>
                <p class="card-text">{{artikel.isi|truncatewords:10}}</p>
                <a href="{% url 'artikel:detail' artikel.slug %}" class="card-link">Selengkapnya</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>




{% endblock contents %}