project-3/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static
from .views import loginView, logoutView

urlpatterns = [
    re_path('', include(('store.urls', 'store'), namespace='store')),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project-3/store/urls.py
from django.urls import path, re_path
from .views import (
    store,
    cart,
    checkout,
    updateItem,
    processOrder,
    productDetail
)

urlpatterns = [
    re_path('detail/(?P<slugInput>[\w-]+)', productDetail, name='detail'),
    path('', store, name='store'),
    path('cart/', cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('update_item/', updateItem, name='update'),
    path('process_order/', processOrder, name='process_order')
]

project-3/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class Customer(models.Model):
    user    = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name    = models.CharField(max_length=200, null=True)
    email   = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name        = models.CharField(max_length=200, null=True)
    price       = models.FloatField()
    image       = models.ImageField(null=True, blank=True)
    description = models.TextField()
    digital     = models.BooleanField(default=False, null=True, blank=False)
    slug        = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.name)
        super().save()

    def __str__(self):
        return self.name
    
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Order(models.Model):
    customer        = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered    = models.DateTimeField(auto_now_add=True)
    complete        = models.BooleanField(default=False, null=True, blank=True)
    transaction_id  = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
class OrderItem(models.Model):
    product     = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order       = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity    = models.IntegerField(default=0, null=True, blank=True)
    data_added  = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

class ShippingAddress(models.Model):
    customer    = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order       = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address     = models.CharField(max_length=200, null=True)
    kelurahan   = models.CharField(max_length=200, null=True)
    kecamatan   = models.CharField(max_length=200, null=True)
    city        = models.CharField(max_length=200, null=True)
    zipcode     = models.CharField(max_length=200, null=True)
    data_added  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address 

project-3/ecommerce/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

def loginView(request):
    context = {
        'page_title': 'LOGIN'
    }
    
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('store:store')
        else:
            return render(request, 'login.html', context)


    if request.method == 'POST':
        name_login = request.POST['username']
        pass_login = request.POST['password']

        user = authenticate(request, username=name_login, password=pass_login)
        if user is not None:
            login(request,user)
            return redirect('store:store')
        else:
            return redirect('login')

@login_required
def logoutView(request):
    context = {
        'page_title':'LOGOUT'
    }

    if request.method == 'POST':
        if request.POST['logout'] == 'Submit':
            logout(request)
        return redirect('store:store')
    
    return render(request, 'logout.html', context)

project-3/store/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *
from .utils import cartData, guestOrder
from django.views.generic import DetailView
import json
import datetime
# Create your views here.
# class productDetail(DetailView):
#     model = Product
#     template_name = 'store/product_detail.html'
#     context_object_name = 'product'

def productDetail(request, slugInput):
    data = cartData(request)
    cartItems = data['cartItems']
    products = Product.objects.get(slug=slugInput)
    print(products)
    context = {
        'products': products,
        'cartItems' : cartItems,
    }
    return render(request, 'store/product_detail.html', context)

def store(request):
    data = cartData(request)

    cartItems = data['cartItems']
    products = Product.objects.all()
    context = {
        'page_title': 'OOPSHOODIE',
        'products': products,
        'cartItems':cartItems,
    }
    return render(request, 'store/store.html', context)


def cart(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'page_title': 'Cart',
        'cartItems': cartItems,
        'items' : items,
        'order': order,
        }
    
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'page_title': 'Checkout',
        'items' : items,
        'order': order,
        'cartItems':cartItems,
        }
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('action: ', action)
    print('productId: ',productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)
        
    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
            ShippingAddress.objects.create(
                customer = customer,
                order = order,
                address = data['shipping']['address'],
                kelurahan = data['shipping']['kelurahan'],
                kecamatan = data['shipping']['kecamatan'],
                city = data['shipping']['city'],
                zipcode = data['shipping']['zipcode'],
            )

    return JsonResponse('Payment completed...', safe=False)

project-3/store/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
{% block contents %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>Total: <strong>Rp. {{order.get_cart_total|floatformat:3}}</strong></h5></th>
                    <th>
                        <a style="float: right; margin: 5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>
        <br>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex: 2"></div>
                <div style="flex: 2"><strong>Item</strong></div>
                <div style="flex: 1"><strong>Price</strong></div>
                <div style="flex: 1"><strong>Quantity</strong></div>
                <div style="flex: 1"><strong>Total</strong></div>
            </div>
            
            {% for item in items %}
            <div class="cart-row">
                <div style="flex: 2;"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex: 2"><p>{{item.product.name}}</p></div>
                <div style="flex: 1"><p>Rp. {{item.product.price|floatformat:3}}</p></div>
                <div style="flex: 1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static 'img/arrow-up.png' %}">
                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static 'img/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex: 1"><p>Rp. {{item.get_total|floatformat:3}}</p></div>
            </div>
            {% endfor %}
                
                
        </div>
    </div>
</div>
    
{% endblock contents %}
    

project-3/store/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}

{% block contents %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    {% csrf_token %}
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email...">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Informasi Pengguna</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" placeholder="Alamat...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="kelurahan" placeholder="Kelurahan...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="kecamatan" placeholder="Kecamatan...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" placeholder="Kota...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="Kode Pos...">
                        </div>
                    </div>
                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>

            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Option</small>
                <div id="paypal-button-container"></div>
                <!-- <button id="make-payment">Make Payment</button> -->
            </div>
        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>

                {% for item in items %}
                <div class="cart-row">
                    <div style="flex: 2;"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex: 2"><p>{{item.product.name}}</p></div>
                    <div style="flex: 1"><p>Rp. {{item.product.price|floatformat:3}}</p></div>
                    <div style="flex: 1"><p>x{{item.quantity}}</p></div>
                </div>
    
                {% endfor %}
    
                <h5>Items:      {{order.get_cart_items}}</h5>
                <h5>Total:      Rp. {{order.get_cart_total|floatformat:3}}</h5>
            </div>
        </div>
    </div>

    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script>
        paypal.Buttons({
            createOrder : function(data, actions){
                return actions.order.create({
                    purchase_units : [{
                        amount : {
                            value : '0.01'
                        }
                    }]
                });
            },
            onApprove: function(data, actions){
                return actions.order.capture().then(function(details){
                    alert('Transaksi diselesaikan Oleh ' + details.payer.name.given_name + '!');
                })
            }
        }).render('#paypal-button-container');
    </script>

    <script type="text/javascript">
        var shipping = '{{order.shipping}}'
        var total = '{{order.get_cart_total|floatformat:3}}'
    
        if (shipping == 'False'){
            document.getElementById('shipping-info').innerHTML = ''
        }
        if (user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
        }
    
    
        if (shipping == 'False' && user != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add('hidden');
            document.getElementById('payment-info').classList.remove('hidden');
        }
    
        
    
        var form = document.getElementById('form')

        csrftoken = form.getElementsByTagName('input')[0].value
        console.log('New Token: ', form.getElementsByTagName('input')[0].value)
        
        form.addEventListener('submit', function(e){
            e.preventDefault()
            console.log('Form Submitted...')
            document.getElementById('form-button').classList.add('hidden');
            document.getElementById('payment-info').classList.remove('hidden');
            })
    
        // document.getElementById('make-payment').addEventListener('click', function(e){
        //     submitFormData()
        // })
    
        function submitFormData(){
            console.log('payment button clicked')
    
            var userFormData = {
                'name':null,
                'email':null,
                'total':total,
            }
            var shippingInfo = {
                'address':null,
                'kelurahan':null,
                'kecamatan':null,
                'city':null,
                'zipcode':null,
            }
    
            if (shipping != 'False'){
                shippingInfo.address = form.address.value
                shippingInfo.kelurahan = form.kelurahan.value
                shippingInfo.kecamatan = form.kecamatan.value
                shippingInfo.city = form.city.value
                shippingInfo.zipcode = form.zipcode.value
            }
    
            if (user == 'AnonymousUser'){
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }
            var url = '/process_order/'
            fetch(url,{
                method : 'POST',
                headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'form':userFormData, 'shipping':shippingInfo})
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('success: ', data);
                alert('Transaction Completed');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/'
                window.location.href = '{% url "store:store" %}'
            })
        }
    </script>
{% endblock contents %}
    

project-3/store/templates/store/product_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{products.name}}
{% endblock page_title %}

{% block contents %}
<div class="row">
    <div class="col-sm">
        <div class="box">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">Continue Shopping</a>
        </div>
        <br>
        <img class="img-detail" src="{{products.imageURL}}">
    </div>
    <div class="col-md-6">
        <h5>{{products.name}}</h3>
        <h4><strong>Rp. {{products.price|floatformat:3}}</strong></h4>
        <br>
        <h6>Deskripsi Produk :</h6>
        <p>{{products.description}}</p>
    </div>
    <div class="col-sm">
        <button data-product={{products.id}} data-action="add" class="btn btn-success add-btn update-cart">Add to Cart</button>
    </div>
</div>
{% endblock contents %}
    
    

project-3/store/templates/store/store.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
    {% block contents %}
        <div class="row">
            
            {% for product in products %}
                
            <div class="col-lg-4">
                <img class="thumbnail rounded mx-auto d-block" src="{{product.imageURL}}">
                <div class="box-element product">
                    <h6><strong>{{product.name}}</strong></h6>
                    <hr>
                    
                    <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                    <a class="btn btn-outline-success" href="{% url 'store:detail' product.slug %}">View</a>
                    <h4 style="display: inline-block;"><strong>Rp. {{product.price|floatformat:3}}</strong></h4>
                </div>
            </div>

            {% endfor %}

        </div>
    {% endblock contents %}
        

project-3/templates/base.html
{% load static %}

<html lang="en">
<head>
    <title>
        
        {% block page_title %}
            
        {% endblock page_title %}
            
    </title>

    {% include 'snippets/styles.html' %}

    {% include 'snippets/head_scripts.html' %}

</head>
<body>
    
    {% if request.user.is_authenticated %}
    {% include 'snippets/navbar_logout.html' %}
    {% else %}
    {% include 'snippets/navbar_login.html' %}
    {% endif %}
        
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <div class="container">
        <br>
        {% block contents %}
        
        {% endblock contents %}

    </div>
        
    {% include 'snippets/body_scripts.html' %}
</body>
</html>

project-3/templates/login.html
{% extends 'base.html' %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
    {% block contents %}
        <h1>LOGIN</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Username</label>
              <input type="text" class="form-control" name="username" id="username">
            <div class="mb-3">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" name="password" id="password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    {% endblock contents %}
        

project-3/templates/logout.html
{% extends 'base.html' %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <p>Apakah anda yakin akan logout?</p>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="logout">
    </form>
{% endblock contents %}
        

project-3/templates/snippets/body_scripts.html
{% load static %}

<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

project-3/templates/snippets/head_scripts.html
<script>
    var user = '{{request.user}}'

    function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getToken('csrftoken');

function getCookie(name){
    var cookieArr = document.cookie.split(';');

    for(var i = 0; i < cookieArr.length; i++) {
        var cookiePair = cookieArr[i].split('=');

        if(name == cookiePair[0].trim()) {
            return decodeURIComponent(cookiePair[1]);
        }
    }
    return null
}

var cart = JSON.parse(getCookie('cart'))

if (cart == undefined){
    cart = {}
    console.log('Cart was created!')
    document.cookie = 'cart = ' + JSON.stringify(cart) + ';domain=;path=/'
}
console.log('Cart: ', cart)
</script>

project-3/templates/snippets/navbar_login.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'store:store' %}">
      <img id="img-icon" src="{% static 'img/oops.jpg' %}">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'store:store' %}">Store</a>
        </li>
      </ul>
      <p style="color: white; margin: auto;">
      <img id="img-icon" src="{% static 'img/logo_akun.jpg' %}">
        {{user}}
      </p> 
    </div>
    <div class="form-inline my-2 my-lg-0">
        <a href="{% url 'login' %}" class="btn btn-warning me-2">Login</a>
      </div>
          <a href="{% url 'store:cart' %}">
              <img id="cart-icon" src="{% static 'img/cart.png' %}">
          </a>
          <p id="cart-total">{{cartItems}}</p>
        </div>
      </div>
  </nav>

project-3/templates/snippets/navbar_logout.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'store:store' %}">
      <img id="img-icon" src="{% static 'img/oops.jpg' %}">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'store:store' %}">Store</a>
        </li>
      </ul>
      <p style="color: white; margin: auto;">
      <img id="img-icon" src="{% static 'img/logo_akun.jpg' %}">
        {{user}}
      </p> 
    </div>
    <div class="form-inline my-2 my-lg-0">
        <a href="{% url 'logout' %}" class="btn btn-danger me-2">Logout</a>
      </div>
          <a href="{% url 'store:cart' %}">
              <img id="cart-icon" src="{% static 'img/cart.png' %}">
          </a>
          <p id="cart-total">{{cartItems}}</p>
        </div>
      </div>
  </nav>

project-3/templates/snippets/styles.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">