project-5/main/urls.py
from django.urls import path, re_path
from . import views


app_name = "main"

urlpatterns = [
	path('', views.index_view.as_view(), name="home"),
    path('contact/', views.contact_view, name='contact_view'),
    path('certificate/', views.certificates_view.as_view(), name='certificate'),
    re_path('reporting/(?P<page>\d+)', views.reporting_view.as_view(), name='reports'),
    path('reporting/<slug:slug>', views.reporting_result_view.as_view(), name="reporting"),
]

project-5/resume_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project-5/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

# Create your models here.
    
class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = 'User Profile'
        verbose_name = 'User Profile'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to='avatar')
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    cv = models.FileField(blank=True, null=True, upload_to='cv')

    def __str__(self) :
        return f'{self.user.first_name} {self.user.last_name}'
    
class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name
    
class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class ReportingResult(models.Model):
    class Meta:
        verbose_name_plural = 'Reporting Results'
        verbose_name = 'Reporting Result'
        ordering = ['date']

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image_one = models.ImageField(blank=True, null=True, upload_to="portfolio")
    image_two = models.ImageField(blank=True, null=True, upload_to="portfolio")
    image_three = models.ImageField(blank=True, null=True, upload_to="portfolio")
    image_four = models.ImageField(blank=True, null=True, upload_to="portfolio")
    video = models.FileField(upload_to='videos', null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    source = models.CharField(max_length=200, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(ReportingResult, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"
    
class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

project-5/main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactProfile
		fields = ['name', 'email', 'message']

project-5/main/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib import messages
from .models import Certificate, ReportingResult
from django.shortcuts import render, redirect
from .forms import ContactForm

# Create your views here.
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you, I will contact you soon')
            return redirect('/')
    else:
        form = ContactForm()

    return render(request, 'main/index.html', {'form': form})

class index_view(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        reporting_results = ReportingResult.objects.filter(is_active=True).order_by('-date')[:6]

        context['reporting_results'] = reporting_results

        return context
    
class certificates_view(ListView):
    model = Certificate
    template_name = 'main/certificate.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        certificates = Certificate.objects.filter(is_active=True)

        context['certificates'] = certificates

        return context
    
class reporting_view(ListView):
    model = ReportingResult
    template_name = 'main/reporting.html'
    context_object_name = 'reporting'
    paginate_by = 10

    def get_queryset(self):
        return ReportingResult.objects.filter(is_active=True).order_by('-date')
    
class reporting_result_view(DetailView):
    model = ReportingResult
    template_name = "main/reporting-detail.html"

project-5/main/templates/main/base.html
{% load static %}
<html>
    <head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/slider.css' %}" />
	</head>
    <body class="is-preload">
		<header id="header">
			<div class="inner">
				<img class="image avatar" src="{{me.userprofile.avatar.url}}" alt="">
				<h1><strong>{{me.first_name}} {{me.last_name}}</strong></h1>
				<h4>{{me.userprofile.title}}</h4>
			</div>
		</header>
		
        {% block content %}
        {% endblock %}

        {% include 'main/partials/footer.html' %}

        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'assets/js/jquery.poptrox.min.js' %}"></script>
		<script src="{% static 'assets/js/browser.min.js' %}"></script>
		<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
		<script src="{% static 'assets/js/util.js' %}"></script>
		<script src="{% static 'assets/js/main.js' %}"></script>
		<script src="{% static 'assets/js/slider.js' %}"></script>
    </body>
</html>

project-5/main/templates/main/certificate.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} My Certificates {% endblock %}

{% block content %}
<div id="main">
    <section id="one">
        <h2>My Certificates</h2>
        <div class="row">
            {% for c in certificates|dictsort:'date' reversed %}
            {% if c.is_active %}
            <article class="col-6 col-12-xsmall work-item">
                <img src="{{c.image.url}}" alt="" height="400" width="400" />
                <h3>{{c.name|title}}</h3>
                <h5>{{c.title}}</h5>
                <p>{{c.date.date}}</p>
            </article>
            {% endif %}
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

project-5/main/templates/main/contact.html
<!-- {% load static %}

<section id="three">
    <h2 id="contactme">Get In Touch</h2>
    <p>Hello! If you want to contact me or want to provide feedback about my work, you can send a message via the column listed or the contact provided below. Thank You!</p>
    <div class="row">
        <div class="col-8 col-12-small">
            <form id="contactForm" method="post" action="/">
                {% csrf_token %}
                <div class="row gtr-uniform gtr-50">
                    <div class="col-6 col-12-xsmall"><input type="text" name="name" id="name" placeholder="Name" />{{form.name}}</div>
                    <div class="col-6 col-12-xsmall"><input type="email" name="email" id="email" placeholder="Email" />{{form.email}}</div>
                    <div class="col-12"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea>{{form.message}}</div>
                </div>
            </form>
            <form id="contactForm" method="POST" action="/contact/">
                {% csrf_token %}
                    <label for="name">Name</label>
                    {{form.name}}
        
                    <label for="email">Email</label>
                    {{form.email}}
        
                    <label for="subject">Message</label>
                    {{form.message}}
        
                    <input class='btn btnPrimary' type="submit" value="Submit">
                </form>
            <ul class="actions">
                <li><input type="submit" value="Send Message" /></li>
            </ul>
        </div>
        <div class="col-4 col-12-small">
            <ul class="labeled-icons">
                <li>
                    <h3 class="icon solid fa-home"><span class="label">Address</span></h3>
                    H. Liun Street No. 86a Petukangan Utara, Pesanggrahan, Jakarta Selatan, 12260
                </li>
                <li>
                    <h3 class="icon solid fa-mobile-alt"><span class="label">Phone</span></h3>
                    +62 851 5632 5387
                </li>
                <li>
                    <h3 class="icon solid fa-envelope"><span class="label">Email</span></h3>
                    faishalprtm@gmail.com
                </li>
            </ul>
        </div>
    </div>
</section> -->

project-5/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} Faishal's Portfolio {% endblock %}

{% block content %}
<!-- Main -->
<div id="main">

    <!-- One -->
        <section id="one">
            <header class="major">
                <h2>About Me</h2>
            </header>
            <p>{{me.userprofile.bio}}</p>
        </section>

    <!-- Two -->
        <section id="two">
            <h2>Recent Work</h2>
            <div class="row">
            {% for a in reporting_results|dictsort:'date' reversed %}
            {% if a.is_active %}
                <article class="col-6 col-12-xsmall work-item">
                    {% if a.image_one %}
                   <a href="{% url 'main:reporting' slug=a.slug %}"><img src="{{a.image_one.url}}" alt="" height="300" width="400"></a>
                   {% else %}
                   <a href="{% url 'main:reporting' slug=a.slug %}"><img src="{{a.video.url}}" alt="" height="300" width="400"></a>
                   {% endif %}
                    <h4></h4>
                    <h5>{{a.name}}</h5>
                    <p>{{a.date.date}}</p>
                </article>
            {% endif %}
            {% endfor %}
            </div>
            <ul class="actions">
                <li><a href="{% url 'main:reports' 1 %}" class="button">View All</a></li>
            </ul>
        </section>

    <!-- Three -->
        <section id="three">
            <h2 id="contactme">Get In Touch</h2>
            <p>Hello! If you want to contact me or want to provide feedback about my work, you can send a message via the column listed or the contact provided below. Thank You!</p>
            <div class="row">
                <div class="col-8 col-12-small">
                    <form id="contactForm" method="post" action="{% url 'main:contact_view' %}">
                        {% csrf_token %}
                        <div class="row gtr-uniform gtr-50">
                            <div class="col-6 col-12-xsmall"><input type="text" name="name" id="name" placeholder="Name" /></div>
                            <div class="col-6 col-12-xsmall"><input type="email" name="email" id="email" placeholder="Email" /></div>
                            <div class="col-12"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea></div>
                        </div>
                        <br>
                        <ul class="actions">
                            <li><input type="submit" value="Send Message" /></li>
                        </ul>
                    </form>
                    {% include 'main/partials/message.html' %}
                </div>
                <div class="col-4 col-12-small">
                    <ul class="labeled-icons">
                        <li>
                            <h3 class="icon solid fa-home"><span class="label">Address</span></h3>
                            H. Liun Street No. 86a Petukangan Utara, Pesanggrahan, Jakarta Selatan, 12260
                        </li>
                        <li>
                            <h3 class="icon solid fa-mobile-alt"><span class="label">Phone</span></h3>
                            +62 851 5632 5387
                        </li>
                        <li>
                            <h3 class="icon solid fa-envelope"><span class="label">Email</span></h3>
                            faishalprtm@gmail.com
                        </li>
                    </ul>
                </div>
            </div>
        </section>
</div>
{% endblock%}

project-5/main/templates/main/partials/footer.html
{% load static %}

<footer id="footer">
    <div class="inner">
        <ul class="icons">
            <li><a href="https://twitter.com/faishalprtm" class="icon brands fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
            <li><a href="https://linkedin.com/in/faishalprtm" class="icon brands fa-linkedin" target="_blank"><span class="label">linkedin</span></a></li>
            <li><a href="https://instagram.com/faishalprtm" class="icon brands fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
            <li><a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=faishalprtm@gmail.com" class="icon solid fa-envelope"><span class="label" target="_blank">Email</span></a></li>
        </ul>
        <ul class="copyright">
            <li><a href="{% url 'main:home' %}">Home</a></li>
            <li><a href="{% url 'main:home' %}#contactme">Contact Me</a></li>
            <li><a href="{% url 'main:certificate' %}">My Certificates</a></li>
        </ul>
        <ul class="copyright">
            <li><a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download CV</a></li>
        </ul>
    </div>
</footer>

project-5/main/templates/main/partials/message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

project-5/main/templates/main/reporting-detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} Reporting Result {% endblock %}

{% block content %}
<div id="main">
    <section id="two">
        <div class="slideshow-container">

            <!-- Full-width images with number and caption text -->
            {% if object.image_one %}
            <div class="mySlides fade">
              <div class="numbertext">1 / 4</div>
              <img src="{{object.image_one.url}}" alt="" height="400" width="600" class="center" >
            </div>
            {% if object.video %}
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
            {% endif %}
            {% endif %}
          
            {% if object.image_two %}
            <div class="mySlides fade">
              <div class="numbertext">2 / 4</div>
              <img src="{{object.image_two.url}}" alt="" height="400" width="600" class="center" >
            </div>
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
            {% endif %}
          
            {% if object.image_three %}
            <div class="mySlides fade">
              <div class="numbertext">3 / 4</div>
              <img src="{{object.image_three.url}}" alt="" height="400" width="600" class="center" >
            </div>
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
            {% endif %}

            {% if object.image_four %}
            <div class="mySlides fade">
              <div class="numbertext">4 / 4</div>
              <img src="{{object.image_four.url}}" alt="" height="400" width="600" class="center" >
            </div>
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
            {% endif %}

            {% if object.video %}
            <div class="mySlides fade">
                <video height="400" width="600" class="center" controls autoplay>
                    <source src="{{object.video.url}}" type="video/mp4">
                </video>
            </div>
            {% endif %}
            
          </div>
          <br>
          
        <h3></h3>
        <p>{{object.body}}</p>
        <ul class="actions">
            <li><a href="{{object.source}}" class="button">Source</a></li>
        </ul>
    </section>
</div>
{% endblock %}

project-5/main/templates/main/reporting.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} My Reports {% endblock %}

{% block content %}
<div id="main">
    <section id="one">
        <h2>My All Reports</h2>
        <div class="row">
            {% for r in reporting|dictsort:'date' reversed %}
            {% if r.is_active %}
            <article class="col-6 col-12-xsmall work-item">
                {% if r.image_one %}
                <a href="{% url 'main:reporting' slug=r.slug %}"><img src="{{r.image_one.url}}" alt="" height="300" width="400"></a>
                {% else %}
                <a href="{% url 'main:reporting' slug=r.slug %}"><img src="{{r.video.url}}" alt="" height="300" width="400"></a>
                {% endif %}
                <h4></h4>
                <h5>{{r.name}}</h5>
                <p>{{r.date.date}}</p>
            </article>
            {% endif %}
            {% endfor %}
        </div>
        
        {% if is_paginated %}
        <ul style="display: flexbox; margin-left: 280px;">
            
            {% if page_obj.has_previous %}
                <a style="margin-right: 10px;" href="{% url 'main:reports' page_obj.previous_page_number %}">Previous</a>
            {% else %}
                <a style="margin-right: 10px;">Previous</a>
            {% endif %}
            
            {% for page in paginator.page_range %}
            {% if page is page_obj.number %}
                <span style="margin-right: 10px;" href="#">{{page}}</span>
            {% else %}
                <a style="margin-right: 10px;" href="{% url 'main:reports' page %}">{{page}}</a>
            {% endif %}
            {% endfor %}
                
            {% if page_obj.has_next %}
                <a style="margin-right: 10px;" href="{% url 'main:reports' page_obj.next_page_number %}">Next</a>
            {% else %}
                <a style="margin-right: 10px;">Next</a>
            {% endif %}
        </ul>
        {% endif %}
    </section>
</div>
{% endblock %}

project-5/main/templates/main/snippets/scripts.html
{% load static %}

<script src="{% static 'popper/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

project-5/main/templates/main/snippets/styles.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">