project-1/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('sosmed.urls', 'sosmed'), namespace='sosmed')),
    # path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

project-1/sosmed/urls.py
from django.urls import path, re_path
from .views import (
    sosmedListView,
    sosmedDeleteView,
    sosmedFormView,
)

urlpatterns = [
    re_path('delete/(?P<delete_id>[0-9]+)$', sosmedDeleteView.as_view(), name='delete'),
    re_path('update/(?P<update_id>[0-9]+)$', sosmedFormView.as_view(mode='update'), name='update'),
    path('create/', sosmedFormView.as_view(), name='create'),
    path('', sosmedListView.as_view(), name='list'),
]

project-1/sosmed/models.py
from django.db import models

# Create your models here.


class instagram(models.Model):
    nama_depan = models.CharField(max_length=100)
    nama_belakang = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    sosial_media = models.CharField(max_length=100)

    def __str__(self):
        return '{}.{}'.format(self.id, self.username)

project-1/sosmed/forms.py
from django import forms
from .models import instagram


class instagramForm(forms.ModelForm):
    class Meta:
        model = instagram
        fields = [
            'nama_depan',
            'nama_belakang',
            'username',
            'sosial_media',
        ]

project-1/sosmed/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, RedirectView, View
# Create your views here.
from .models import instagram
from .forms import instagramForm


class sosmedSubList:

    def get_list_data(self, get_request):
        if len(get_request) == 0:
            subList = instagram.objects.all()
        elif get_request.__contains__('sosial_media_filter'):
            subList = instagram.objects.filter(
                sosial_media=get_request['sosial_media_filter'])
        else:
            subList = instagram.objects.none()

        return subList


class sosmedListView(sosmedSubList, TemplateView):
    template_name = 'sosmed/list.html'

    def get_context_data(self, *args, **kwargs):
        # akun = instagram.objects.all()
        listAkun = self.get_list_data(self.request.GET)
        listContent = instagram.objects.values_list(
            'sosial_media', flat=True).distinct()
        print(listContent)
        context = {
            'page_title': 'Social Media',
            'akun': listAkun,
            'content': listContent,
        }
        return context


class sosmedDeleteView(RedirectView):
    pattern_name = 'sosmed:list'
    permanent = False
    query_string = False

    def get_redirect_url(self, *args, **kwargs):
        delete_id = kwargs['delete_id']
        print(delete_id)
        instagram.objects.filter(id=delete_id).delete()
        return super().get_redirect_url()


class sosmedFormView(View):
    template_name = 'sosmed/create.html'
    form = instagramForm()
    mode = None
    context = {}

    def get(self, *args, **kwargs):
        if self.mode == 'update':
            akunUpdate = instagram.objects.get(id=kwargs['update_id'])
            data = akunUpdate.__dict__
            self.form = instagramForm(initial=data, instance=akunUpdate)

        self.context = {
            'page_title': 'Update Akun',
            'akun_form': self.form,
        }
        return render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if kwargs.__contains__('update_id'):
            akunUpdate = instagram.objects.get(id=kwargs['update_id'])
            self.form = instagramForm(self.request.POST, instance=akunUpdate)

        else:
            self.form = instagramForm(self.request.POST)

        if self.form.is_valid():
            self.form.save()

        return redirect('sosmed:list')

project-1/sosmed/templates/sosmed/create.html
{% extends 'base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{page_title}}</h1>
<form method="POST">
    {% csrf_token %}
    <div class="row mb-3" style="width: 300px;">
      {{akun_form}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock contents %}

project-1/sosmed/templates/sosmed/list.html
{% extends 'base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{page_title}}</h1>
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Sosial Media
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{% url 'sosmed:list' %}">Semua Sosial Media</a>

            {% for content in content %}
            <a class="dropdown-item" href="{% url 'sosmed:list' %}?sosial_media_filter={{content}}">
                {{content}}
            </a>
            {% endfor %}

        </li>
    </ul>
</div>

<table class="table mt-2">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Username</th>
            <th scope="col">Sosial Media</th>
            <th scope="col">Hapus</th>
            <th scope="col">Ubah</th>
        </tr>
    </thead>
    <tbody>

        {% for akun_ig in akun %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{akun_ig.nama_depan}}</td>
            <td>{{akun_ig.nama_belakang}}</td>
            <td>{{akun_ig.username}}</td>
            <td>{{akun_ig.sosial_media}}</td>
            <td><a href="{% url 'sosmed:delete' akun_ig.id %}" class="btn btn-danger">Delete</a></td>
            <td><a href="{% url 'sosmed:update' akun_ig.id %}" class="btn btn-warning">Update</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'sosmed:create' %}">Tambah</a>
{% endblock contents %}

project-1/templates/base.html
<html lang="en">

<head>
    <title>

        {% block title %}

        {% endblock title %}

    </title>
    {% include 'snippets/styles.html' %}
</head>

<body>
    <div class="container">

        {% block contents %}

        {% endblock contents %}

    </div>
    {% include 'snippets/scripts.html' %}
</body>

</html>

project-1/templates/index.html
{% extends 'base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{page_title}}</h1>
{% endblock contents %}